services:
  ms-loan:
    build:
      context: ./ms-loan
      dockerfile: Dockerfile
    container_name: ms-loan
    ports:
      - "8082:8080"
    environment:
      - APP_NAME=ms-loan
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_NAME=loan_capcred_db
      - RABBITMQ_HOST=rabbitmq
      - MS_AUTH_USER_URL=http://ms-auth-user:8080/api/users
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - postgres
      - rabbitmq
  ms-payment:
    build:
      context: ./ms-payment
      dockerfile: Dockerfile
    container_name: ms-payment
    ports:
      - "8083:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_NAME=payment_capcred_db
      - RABBITMQ_HOST=rabbitmq
      - MS_AUTH_USER_URL=http://ms-auth-user:8080/api/users
    depends_on:
      - postgres
      - rabbitmq
  ms-notification:
    build:
      context: ./ms-notification
      dockerfile: Dockerfile
    container_name: ms-notification
    ports:
      - "8084:8080"
    env_file:
      - ./.env
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_NAME=notification_capcred_db
      - RABBITMQ_HOST=rabbitmq
      - MAIL_HOST=mailhog
    depends_on:
      - postgres
      - rabbitmq
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  postgres:
    image: postgres:17-alpine3.22
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=gadmin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki