global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ms-loan'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-loan:8080']

  - job_name: 'ms-payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-payment:8080']

  - job_name: 'ms-notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-notification:8080']