server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ${APP_NAME:ms-loan}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan_capcred_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

broker:
  exchange:
    loan: ${LOAN_EXCHANGE:loan.events}
  queue:
    loan.created: ${LOAN_CREATED_QUEUE:loan.created}
    loan.approved: ${LOAN_APPROVED_QUEUE:loan.approved}
    loan.rejected: ${LOAN_REJECTED_QUEUE:loan.rejected}
    loan.completed.loan: ${LOAN_COMPLETED_LOAN_QUEUE:loan.completed.loan}

resilience4j:
  circuitbreaker:
    configs:
      default: # Configuração padrão para todos os CBs
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10 # Considera as últimas 10 chamadas
        failureRateThreshold: 50 # Se mais de 50% falhar, abra o circuito
        waitDurationInOpenState: 10s # Tempo que o circuito fica totalmente aberto
        permittedNumberOfCallsInHalfOpenState: 3 # Número de chamadas para testar no estado HALF_OPEN
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      # NOME ESPECÍFICO DO SEU DISJUNTOR
      user-service-call:
        base-config: default

springdoc:
  api-docs.path: /documentacao
  swagger-ui.path: /documentacao.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

ms.user.url: ${MS_AUTH_USER_URL:http://localhost:8080/api/users}
