server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ${APP_NAME:ms-loan}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan_capcred_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

broker:
  exchange:
    loan: ${LOAN_EXCHANGE:loan.events}
  queue:
    loan.created: ${LOAN_CREATED_QUEUE:loan.created}
    loan.approved: ${LOAN_APPROVED_QUEUE:loan.approved}
    loan.rejected: ${LOAN_REJECTED_QUEUE:loan.rejected}
    loan.completed.loan: ${LOAN_COMPLETED_LOAN_QUEUE:loan.completed.loan}

springdoc:
  api-docs.path: /documentacao
  swagger-ui.path: /documentacao.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

ms.user.url: ${MS_AUTH_USER_URL:http://localhost:8080/api/users}
