spring:
  application:
    name: ms-loan
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:capcred_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

broker:
  queue:
    loan.created: ${LOAN_CREATED_QUEUE:loan.created}
    loan.approved: ${LOAN_APPROVED_QUEUE:loan.approved}
    loan.rejected: ${LOAN_REJECTED_QUEUE:loan.rejected}

springdoc:
  api-docs.path: /documentacao
  swagger-ui.path: /documentacao.html
